# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0018_parking_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitArea',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PermitSubject',
            fields=[
                ('registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='permit',
            name='areas',
            field=models.ManyToManyField(related_name='permits', to='parkings.PermitArea'),
        ),
        migrations.AddField(
            model_name='permit',
            name='subjects',
            field=models.ManyToManyField(related_name='permits', to='parkings.PermitSubject'),
        ),
    ]
