# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0019_permits'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPermit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('subjects', models.CharField(max_length=1000)),
                ('areas', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
