# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0020_permits2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpermit',
            old_name='areas',
            new_name='_areas',
        ),
        migrations.RenameField(
            model_name='flatpermit',
            old_name='subjects',
            new_name='_subjects',
        ),
    ]
