# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0023_permits5'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='permit',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkings.PermitSeries'),
        ),
    ]
