# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0027_auto_20190505_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permit',
            old_name='id',
            new_name='uuid',
        ),
    ]
