# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 21:23
from __future__ import unicode_literals

from django.db import migrations, models


def fill_integer_id(apps, schema_editor):
    permit_model = apps.get_model('parkings', 'Permit')
    id_ = 0
    for permit in permit_model.objects.filter(id=0):
        id_ += 1
        permit.id = id_
        permit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0028_auto_20190505_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            code=fill_integer_id,
            reverse_code=migrations.RunPython.noop),
    ]
