# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0030_auto_20190505_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='permit',
            unique_together=set([('series', 'external_id')]),
        ),
    ]
