# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0033_auto_20190505_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitseries',
            options={'ordering': ('created_at', 'id')},
        ),
    ]
